### ISSUE TITLE
Aspects get carried forward to new versions

### ISSUE THREAD

**Issue by gb-123-git** [zylklab/alfresco-sinadura#12]
Hello,

Bug:
If you upload a new version over the signed version, Sinadura still maintains the aspect 'Digitally Signed=Yes'. This aspect should get reset after new version is uploaded and should be set only once signed again. i.e the properties should be linked with file versions.

Also the icon of 'signed' in thumbnail should disappear once the new version is uploaded.

Thanks

**Comment by CesarCapillas** [comment]
Yes, the aspect is applied to the document when the signature process is started. And the icon is just an evaluator for the applied aspect. 

The aspect was originally implemented for adding some signature properties in future versions, not implemented. Also, it is a way of "tagging" signature processes with Sinadura.

Normally, when a document version is signed, the following versions are signed too.

Anyway, you can easily comment the evaluator in Alfresco config for hiding the evaluator icon, renaming label for Sinadura aspect (let's put "Sinadura" instead "Digitally Signed") for avoiding confussions, even changing code for not using internally the corresponding aspect.

Kind regards.
--C.

**Comment by gb-123-git** [comment]
I think the best thing would be to just move the aspect to be written to the version property and not the file property(if that is possible), that way, when the version is updated and not signed, the aspects will go away.

Is is safe to remove (or comment) the whole aspect in the signModel.xml ? ( I don't wanna do this though since having the sign in the thumbnail is convenient)
Hope commenting would not break anything else ?

**Comment by CesarCapillas** [comment]
A version in Alfresco involves both binary and metadata properties, so that is not possible. You can remove manually the aspect if you want.

It is not recommended nor safe to comment the aspect in signModel.xml

Regards.
--C.

**Comment by gb-123-git** [comment]
Can you point me in the right direction to remove the aspect completely from the code so that it fixes both the issues ? I'll update and re-submit the code. Or would you be able to do it ? (I think since you guys are the Author of this wonderful software, you would be able to do it much faster than me)
