### ISSUE TITLE
Wrongly detecting Sign

### ISSUE THREAD

**Issue by gb-123-git** [zylklab/alfresco-sinadura#13]
Hello,

Bug
If you cancel the signing process at the select certificate screen by clicking cancel the Alfresco still shows the document as signed, even though the document is not actually signed

Thanks

**Comment by CesarCapillas** [comment]
Related to:

https://github.com/zylklab/alfresco-sinadura/issues/12

Kind regards.
--C.

**Comment by gb-123-git** [comment]
This is not related (kind of). the problem here seems to be that the connector 'assumes' the document to be signed by the sinadura service even when the user clicks 'Cancel' at the signing screen. Ideally, there should be a flag by the service to tell the connector if the document was actually signed or not.

**Comment by CesarCapillas** [comment]
Hi:

The component does not check signatures, it only signs with Sinadura. 
If "Cancel button" in Sinadura finishes applying the cited aspect, it may seem that the document is having a digital signature, when there is not (I did not reproduce it).

You are invited to contribute your changes, if it is not the desired behaviour.

Regards.
--C.

**Comment by gb-123-git** [comment]
Just to clarify:
The Desktop Sinadura works fine i.e if you click cancel on the  'Select Certificate Screen', the document shows as not signed (which is right)
However, when you click on 'Sign with Sinadura' on Share, and Click on cancel at the 'Select Certificate Screen' ie the document is still not signed till now, but Alfresco still shows that the Document signed as the aspect is updated.

What I was trying to say is that the aspect should be updated once the signatures are put rather than when Sinadura is launched.

**Comment by gb-123-git** [comment]
@CesarCapillas 
Further steps to reproduce :
If you click on 'Cancel' on the 'Certificate Selection Screen', the program still thinks that the document has been signed (despite it not being signed) and uploads the document. But of you do the same thing (i.e click 'Cancel') on the next screen, the program detects correctly that the file has not been signed.
