### ISSUE TITLE
Sign not visible in Alfresco Share Preview (v6.2.1)

### ISSUE THREAD

**Issue by gb-123-git** [zylklab/alfresco-sinadura#14]
Related to Issue #9 
The code mentioned is not present in the current version of Share (6.2.1)
Any thing else I need to do ?

**Comment by CesarCapillas** [comment]
Hi:

The addon was developed and tested for Alfresco 5.2.
The walkaround for pdfjs was for this version, and it does not apply for Alfresco 6.2.1.

If you find a solution, please send it to include it in README.md instructions.

Kind regards.
--C.

**Comment by gb-123-git** [comment]
The line to find is :

if (data.fieldType === 'Sig')

and follow instructions from #9
