### ISSUE TITLE
Sinadura marking as signed without signing

### ISSUE THREAD

**Issue by edivamD2** [zylklab/alfresco-sinadura#20]
I don't know if it has already been reported.
I am testing SINADURA with Alfresco to sign a batch of documents.
However, an error occurs when I simulate another error.
Scenario:
I create a folder in Alfresco SHARED, upload a large amount of PDF and then use the option to sign a document with SINADURA. When it appears how I should select the certificate, I simply click cancel and the page reloads as if it were signed. However, there is nothing signed. I checked with a signature checker.

I use: Alfresco Community - 6.1.1 (r9d03d2fd-b168) + Sinadura 5.0.9.

![SCENARIO_01](https://user-images.githubusercontent.com/53190997/104761824-3266fb80-5742-11eb-811f-e2208ca892e9.jpg)

![SCENARIO_02](https://user-images.githubusercontent.com/53190997/104761840-3a26a000-5742-11eb-8c87-490a35bca822.jpg)

![SCENARIO_03](https://user-images.githubusercontent.com/53190997/104761879-4a3e7f80-5742-11eb-9874-6406fa9580a4.jpg)

![SCENARIO_04](https://user-images.githubusercontent.com/53190997/104761876-49a5e900-5742-11eb-947d-24abd719292f.jpg)

![SCENARIO_05](https://user-images.githubusercontent.com/53190997/104761873-4874bc00-5742-11eb-9cf7-6feb1ce9ef10.jpg)

**Comment by gb-123-git** [comment]
Yeah. This was Reported in issue #13 .
