### ISSUE TITLE
Sources not available

### ISSUE THREAD

**Issue by hdan1** [zylklab/alfresco-sinadura#6]
Hello,

I can't seem to find the source code. Is the project open source ?

Thank you.

**Comment by CesarCapillas** [comment]
Hi:

This is the github project for sinadura addon for Alfresco, that consists mainly in two AMP modules (and some binary installers of the services and desktop client included in the release). 

https://github.com/zylklab/alfresco-sinadura/tree/master/zk-sinadura-sign-online-alfresco
https://github.com/zylklab/alfresco-sinadura/tree/master/zk-sinadura-sign-online-share

For Sinadura Desktop and services source code you should go to sinadura wiki (they are not migrated to github):

http://www.sinadura.net/es/wik
http://www.sinadura.net/es/wik/-/wiki/sinadura/DevManual300

Regards.
--C.
