### ISSUE TITLE
Problem after signing the file in Sinadura 

### ISSUE THREAD

**Issue by bgn2015** [zylklab/alfresco-sinadura#7]
Hello,

After the file is signed, it can no longer be submitted to the Alfresco. That's what I found in Tomcat logs:

> 2018-01-12 16:36:32,666  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-8] Exception from executeScript - redirecting to status template error: 00120009 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.content.ContentServicePolicies$OnContentUpdatePolicy.onContentUpdate(org.alfresco.service.cmr.repository.NodeRef,boolean) in transaction b4f14518-ee81-4893-99cf-1da44975d4c8
>  org.alfresco.error.AlfrescoRuntimeException: 00120009 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.content.ContentServicePolicies$OnContentUpdatePolicy.onContentUpdate(org.alfresco.service.cmr.repository.NodeRef,boolean) in transaction b4f14518-ee81-4893-99cf-1da44975d4c8
> 	at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:257)
> 	at org.alfresco.repo.policy.TransactionBehaviourQueue.beforeCommit(TransactionBehaviourQueue.java:134)
> 	at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:535)
> 	at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:514)
> 	at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.beforeCommit(TransactionSupportUtil.java:479)
> 	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerBeforeCommit(TransactionSynchronizationUtils.java:95)
> 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerBeforeCommit(AbstractPlatformTransactionManager.java:925)
> 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:738)
> 	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
> 	at org.alfresco.util.transaction.SpringAwareUserTransaction.commit(SpringAwareUserTransaction.java:482)
> 	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:479)
> 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:551)
> 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:619)
> 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:399)
> 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:280)
> 	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
> 	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
> 	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
> 	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466)
> 	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.IllegalArgumentException: Class {http://www.alfresco.com/model/signmodel/1.0}signed has not been defined in the data dictionary
> 	at org.alfresco.repo.policy.ClassPolicyDelegate.getList(ClassPolicyDelegate.java:127)
> 	at org.alfresco.repo.policy.ClassPolicyDelegate.getList(ClassPolicyDelegate.java:112)
> 	at org.alfresco.repo.version.common.AbstractVersionServiceImpl.invokeOnCreateVersion(AbstractVersionServiceImpl.java:271)
> 	at org.alfresco.repo.version.common.AbstractVersionServiceImpl.invokeOnCreateVersion(AbstractVersionServiceImpl.java:191)
> 	at org.alfresco.repo.version.Version2ServiceImpl.createVersion(Version2ServiceImpl.java:271)
> 	at org.alfresco.repo.version.Version2ServiceImpl.createVersion(Version2ServiceImpl.java:118)
> 	at org.alfresco.repo.version.VersionableAspect$2.doWork(VersionableAspect.java:536)
> 	at org.alfresco.repo.version.VersionableAspect$2.doWork(VersionableAspect.java:531)
> 	at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
> 	at org.alfresco.repo.version.VersionableAspect.createVersionImpl(VersionableAspect.java:531)
> 	at org.alfresco.repo.version.VersionableAspect.onContentUpdate(VersionableAspect.java:437)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:174)
> 	at com.sun.proxy.$Proxy69.onContentUpdate(Unknown Source)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:245)
> 	... 43 more

**Comment by CesarCapillas** [comment]
Hi:

First of all, thanks for using Sinadura addon for Alfresco. This error is somehow strange:

```
Caused by: java.lang.IllegalArgumentException: Class {http://www.alfresco.com/model/signmodel/1.0}signed has not been defined in the data dictionary
```
Basically, because the addon does not use this class (content model):

- https://github.com/zylklab/alfresco-sinadura/blob/master/zk-sinadura-sign-online-alfresco/src/main/amp/config/alfresco/extension/model/signModel.xml

So, are you sure that you installed properly the two AMPs ? Maybe you are using other addon for digital signature in Alfresco. Please check:

- https://github.com/keensoft/alfresco-firma-pdf/
- https://github.com/keensoft/alfresco-firma-pdf/blob/master/src/alfresco-components/sign-document/src/main/amp/config/alfresco/extension/model/sign-model.xml

Regards.
--C.

**Comment by bgn2015** [comment]
This are my AMP's installed.

![sinaduraerr](https://user-images.githubusercontent.com/18183156/34929907-345b52ca-f9cf-11e7-9f34-762cb3ccecaa.jpg)

**Comment by bgn2015** [comment]
Or... at least please help me to create a setup needed to run your app (alfresco verson and amp's). Now I run Alfresco 5.

**Comment by CesarCapillas** [comment]
Hi:

The two AMPs seems to be installed.
Then you need to copy sinadura services war (see releases page) in tomcat/webapps and install the sinadura desktop client on your local machine. Finally you need to upload a PDF in Alfresco and use "Sign with Sinadura" action.

Regards.
--C.

**Comment by bgn2015** [comment]
It's working now. Thanks.
