### ISSUE TITLE
Traducción de los datos impresos en la firma

### ISSUE THREAD

**Issue by gmarink** [zylklab/alfresco-sinadura#8]
Hola. donde puedo cambiar la traducción de los datos impresos en la firma (digitally signed by, date, reason y location)?

**Comment by guszylk** [comment]
No se puede cambiar. Es parte de la librería itext y habría que hacer un cambio de código para permitir eso. Si te animas a investigarlo y hacer el cambio sería perfecto. Hace unos años lo investigué y creo que se puede pero hay que hacer un desarrollo para ello

**Comment by gmarink** [comment]
Vou procurar como fazer. Obrigado.
Voy a buscar como hacer. Gracias.
